name: Local Machine CI (Self-hosted)

on:
  workflow_dispatch:

jobs:
  local-test:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run module locally
        run: |
          if (!(Test-Path reports)) { New-Item -ItemType Directory -Path reports }
          
          echo "Запуск аналізу на локальному ПК..."
          python src/data_quality.py > reports/local_run.log 2>&1
          
          echo "Локальна перевірка завершена успішно."

      - name: Upload Local Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: local-pc-report
          path: reports/