name: Project CI (Full Pipeline)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:
    inputs:
      module:
        description: "Оберіть модуль для запуску"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - data_load
          - data_quality
          - research

jobs:
  run-modules:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - module: data_load
            path: data/data_load.py
          - module: data_quality
            path: src/data_quality.py
          - module: research
            path: src/research.py

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        # Цей крок можна залишити для всіх, він швидкий завдяки кешуванню
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        # Додаємо умову сюди
        if: |
          github.event_name != 'workflow_dispatch' || 
          github.event.inputs.module == 'all' || 
          github.event.inputs.module == matrix.module
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Execute Module
        if: |
          github.event_name != 'workflow_dispatch' || 
          github.event.inputs.module == 'all' || 
          github.event.inputs.module == matrix.module
        env:
            # Передаємо секрети в середовище виконання
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          mkdir -p reports/
          python ${{ matrix.path }} > reports/${{ matrix.module }}_run.log 2>&1

      - name: Upload Artifacts
        # Зберігаємо результат тільки якщо крок Execute Module не було пропущено
        if: |
          (github.event_name != 'workflow_dispatch' || 
          github.event.inputs.module == 'all' || 
          github.event.inputs.module == matrix.module) && always()
        uses: actions/upload-artifact@v4
        with:
          name: execution-report-${{ matrix.module }}
          path: reports/
          retention-days: 5
